name: Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        description: "Env to deploy to"
        type: environment
        required: true
    
jobs:
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    environment: Test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    environment: Load-Test
    if: github.event_name == workflow_dispatch
    steps:
      - run: echo "Testing..."
      - run: sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "Step 1 deploying"
          sleep 10
      - run: |
          echo "Step 2 deploying"
          echo "Step 3 deploying"
          echo "Step 4 deploying"
          echo "Step 5 deploying"
      
  Build:
    runs-on: ubuntu-latest
    steps:
      
      - run: |
          echo "TriggerEvent: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref}}"
          echo "Files"

      - uses: actions/checkout@v4

      - name: List files
        run: |
          echo "listing files"
          tree
      
      
  
