name: Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github/**
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      
      - run: |
          echo "TriggerEvent: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref}}"
          echo "Files"

      - uses: actions/checkout@v4

      - name: List files
        run: |
          echo "listing files"
          tree
      
      
  
